name: check
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install required libraries
        run: sudo apt-get update && sudo apt-get install -y python devscripts dh-make debhelper fakeroot python3 python3-pip python3-setuptools python3-wheel ninja-build meson libpam0g-dev libboost-locale-dev python3-dev python3-setuptools libopencv-dev cmake make build-essential clang-tidy

      - uses: actions/checkout@v2

      - name: Build
        run: |
          meson setup build src/pam
          ninja -C build

      - name: Check source code
        run: |
          ninja clang-tidy -C build
